### ISSUE TITLE
Game crashes when breaking waterlogged blocks

### ISSUE THREAD

**Issue by HappyAlexRomania** [AmyMialeeMods/visiblebarriers#32]
When visibility is activated and a waterlogged block is broken, the game crashes with the following error:

The game crashed whilst unexpected error
Error: java.lang.UnsupportedOperationException: No bounds for empty shape.

Here's the Crash report:

---- Minecraft Crash Report ----

Time: 2023-07-30 06:08:51
Description: Unexpected error

java.lang.UnsupportedOperationException: No bounds for empty shape.
	at net.minecraft.class_265.method_1107(class_265.java:49)
	at net.minecraft.class_702.method_3054(class_702.java:517)
	at net.minecraft.class_310.method_1590(class_310.java:1694)
	at net.minecraft.class_310.method_1508(class_310.java:2063)
	at net.minecraft.class_310.method_1574(class_310.java:1883)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

The crash happened on fabric 1.20.1

**Comment by AmyMialee** [comment]
i believe this is fixed, reopen if i'm mistaken
